/**
 * Central icon component — maps semantic names to Lucide SVG icons.
 * Replaces all emoji icons throughout the proposal.
 */

import {
  Target,
  Lightbulb,
  Search,
  CheckCircle2,
  Bot,
  BarChart3,
  Settings2,
  ShieldCheck,
  Lock,
  Eye,
  FileText,
  BookOpen,
  Scroll,
  Workflow,
  Layers,
  Database,
  Cloud,
  Link2,
  Key,
  UserCircle2,
  Users,
  Smartphone,
  RefreshCw,
  TrendingUp,
  MessageSquare,
  Cpu,
  Zap,
  Wrench,
  Handshake,
  FlaskConical,
  Compass,
  DollarSign,
  Building2,
  Download,
  AlertTriangle,
  Info,
  XCircle,
  Bell,
  Mail,
  Sheet,
  FolderOpen,
  LayoutDashboard,
  ClipboardList,
  PackageCheck,
  Telescope,
  HelpCircle,
  type LucideProps,
} from "lucide-react";

const iconMap: Record<string, React.FC<LucideProps>> = {
  // Section headings
  target: Target,
  lightbulb: Lightbulb,
  search: Search,
  check: CheckCircle2,
  bot: Bot,
  chart: BarChart3,
  settings: Settings2,
  shield: ShieldCheck,
  lock: Lock,
  eye: Eye,
  file: FileText,
  book: BookOpen,
  scroll: Scroll,
  workflow: Workflow,
  layers: Layers,
  database: Database,
  cloud: Cloud,
  link: Link2,
  key: Key,
  user: UserCircle2,
  users: Users,
  smartphone: Smartphone,
  refresh: RefreshCw,
  trending: TrendingUp,
  message: MessageSquare,
  cpu: Cpu,
  zap: Zap,
  wrench: Wrench,
  handshake: Handshake,
  flask: FlaskConical,
  compass: Compass,
  dollar: DollarSign,
  building: Building2,
  download: Download,
  warning: AlertTriangle,
  info: Info,
  xcircle: XCircle,
  bell: Bell,
  mail: Mail,
  sheet: Sheet,
  folder: FolderOpen,
  dashboard: LayoutDashboard,
  clipboard: ClipboardList,
  package: PackageCheck,
  telescope: Telescope,
  help: HelpCircle,
};

interface IconProps extends LucideProps {
  name: keyof typeof iconMap;
}

export default function Icon({ name, size = 20, ...props }: IconProps) {
  const Component = iconMap[name];
  if (!Component) return null;
  return <Component size={size} {...props} />;
}
